# Generated by Django 3.1.7 on 2022-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
