# Generated by Django 3.1.7 on 2022-01-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
