# Generated by Django 3.1.7 on 2022-02-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20220201_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
